CREATE TABLE users (
  pk SERIAL PRIMARY KEY NOT NULL UNIQUE,
  id UUID NOT NULL UNIQUE,
  first_name VARCHAR,
  last_name VARCHAR,
  producer_name VARCHAR(50) UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);