CREATE TABLE users (
  user_pk BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
  user_id UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
  first_name VARCHAR,
  last_name VARCHAR,
  producer_name VARCHAR(50) UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(3) NOT NULL
);